import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import ThemeLayout from "./themeSettings";
import { gilroy } from "./lib/fonts/gilroy/gilroy";

const inter = Inter({ subsets: ["latin"] });


export const metadata: Metadata = {
  title: "M-Admin",
  description: "Generated by M-Admin Team",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ThemeLayout>
      <html lang="en">
        <body className={gilroy.className}>{children}</body>
      </html>
    </ThemeLayout>
  );
}
